import type { Config } from 'payload'
import { name as packageName } from '../../package.json'

type CustomField = { path?: string }

type BlockLike = {
  slug?: string
  custom?: Record<string, CustomField | undefined>
}

type CollectionOrGlobalLike = {
  custom?: Record<string, CustomField | undefined>
}

function getCustomPath(
  custom: Record<string, CustomField | undefined> | undefined,
  pkg: string
): string | undefined {
  const v = custom?.[pkg]?.path
  return typeof v === 'string' ? v : undefined
}

function splitKey(key: string): { filePath: string; exportName: string; fullKey: string } {
  const hashIdx = key.indexOf('#')
  if (hashIdx >= 0) {
    return {
      filePath: key.slice(0, hashIdx),
      exportName: key.slice(hashIdx + 1) || 'default',
      fullKey: key,
    }
  }
  return {
    filePath: key,
    exportName: 'default',
    fullKey: `${key}#default`,
  }
}

function defaultBlockPath(slug: string): string {
  return `@/components/blocks/${slug}#default`
}

export type GenerateAsyncImportmapOptions = {
  output: string
  packageName?: string
}

export type GenerateAsyncImportmapResult = {
  entries: number
  output: string
}

export async function generateAsyncImportmap(
  config: Config,
  options: GenerateAsyncImportmapOptions
): Promise<GenerateAsyncImportmapResult> {
  const pkg = options.packageName ?? packageName
  const blocks = ((config.blocks ?? []) as unknown as BlockLike[]) ?? []
  const collections = ((config.collections ?? []) as unknown as CollectionOrGlobalLike[]) ?? []
  const globals = ((config.globals ?? []) as unknown as CollectionOrGlobalLike[]) ?? []

  const keys = new Set<string>()

  for (const block of blocks) {
    if (!block.slug) continue
    const explicit = getCustomPath(block.custom, pkg)
    const key = explicit ?? defaultBlockPath(block.slug)
    keys.add(key)
  }

  for (const item of [...collections, ...globals]) {
    const explicit = getCustomPath(item.custom, pkg)
    if (explicit) keys.add(explicit)
  }

  const sortedKeys = [...keys].sort()

  const lines: string[] = []
  lines.push('// This file is generated by `payload-www generate:async-importmap`.')
  lines.push('// Do not edit by hand — re-run the generator after Payload config changes.')
  lines.push('')
  lines.push('/** @type import(\'payload\').ImportMap */')
  lines.push('export const asyncImportMap = {')
  for (const key of sortedKeys) {
    const { filePath, exportName, fullKey } = splitKey(key)
    const jsonKey = JSON.stringify(fullKey)
    lines.push(`  ${jsonKey}: () => import(${JSON.stringify(filePath)}).then((m) => ({ default: m.${exportName} })),`)
  }
  lines.push('}')
  lines.push('')

  const output = lines.join('\n')

  const { writeFile, mkdir } = await import('node:fs/promises')
  const { dirname } = await import('node:path')
  await mkdir(dirname(options.output), { recursive: true })
  await writeFile(options.output, output, 'utf-8')

  return {
    entries: sortedKeys.length,
    output: options.output,
  }
}