// This file is generated by `payload-www generate:async-importmap`.
// Do not edit by hand — re-run the generator after Payload config changes.

/** @type import('payload').ImportMap */
export const asyncImportMap = {
  "@/app/(frontend)/(pages)/[locale]/posts/[slug]/page#default": () => import("@/app/(frontend)/(pages)/[locale]/posts/[slug]/page").then((m) => ({ default: m.default })),
  "@/app/(frontend)/(pages)/[locale]/posts/category/[slug]/render#default": () => import("@/app/(frontend)/(pages)/[locale]/posts/category/[slug]/render").then((m) => ({ default: m.default })),
  "@/components/Footer/Component#Footer": () => import("@/components/Footer/Component").then((m) => ({ default: m.Footer })),
  "@/components/Header/Component#Header": () => import("@/components/Header/Component").then((m) => ({ default: m.Header })),
  "@/components/blocks/content#default": () => import("@/components/blocks/content").then((m) => ({ default: m.default })),
  "@/components/blocks/cta#default": () => import("@/components/blocks/cta").then((m) => ({ default: m.default })),
  "@/components/blocks/media#default": () => import("@/components/blocks/media").then((m) => ({ default: m.default })),
  "@justanarthur/payload-www/render-pages#PagesPage": () => import("@justanarthur/payload-www/render-pages").then((m) => ({ default: m.PagesPage })),
}
